version: '3.0'
services:
  database:
    image: mongo:4.0.4-xenial
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null
  express:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - database


